--- 
- name: Install GitLab dependencies
  package: name={{ item }} state=present
  with_items:
    - openssh-server
    - postfix
    - curl
    - policycoreutils-python
    - openssh-clients

- name: Add the  GitLab package repository
  shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh | sudo bash

     
- name: Start and Install GitLab 
  shell: sudo EXTERNAL_URL="https://gitlab.example.com" yum install -y gitlab-ee


