--- 
- name: Install GitLab dependencies
  package: name={{ item }} state=present
  with_items:
    - openssh-server
    - postfix
    - curl
    - policycoreutils-python
    - openssh-clients

- name: Add the  GitLab package repository
  shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh | sudo bash

- name: Install GitLab
  yum:
   name: gitlab-ee
   state: present
   
- name: Changing URL to https://192.168.33.103/
  shell: sudo EXTERNAL_URL="https://192.168.33.103/"

