--- 
- name: Install GitLab dependencies
  package: name={{ item }} state=present
  with_items:
    - curl 
    - postfix
    - openssh-server
    - policycoreutils-python
    - openssh-clients

- name: Add the  GitLab package repository
  shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh | sudo bash

     
- name: Start and Install GitLab 
  shell: EXTERNAL_URL="https://192.168.33.103" yum install -y gitlab-ee


