---

- name: Deploy Rocket Chat Server
  hosts: rocket_server
  remote_user: vagrant
  become: yes
    
  roles:
    - rocketchat


- name: Deploy Gitlab Server
  hosts: gitlab_server
  remote_user: vagrant
  become: yes

  roles:
    - gitlab

- name: Deploy Jenkins CI Server
  hosts: jenkins_server
  remote_user: vagrant
  become: yes

  roles:
     - jenkins

- name: Deploy Vault Server
  hosts: vault_server
  remote_user: vagrant
  become: yes

  roles:
    - vault


