---

- hosts: all
  strategy: free
  gather_facts: no
  remote_user: vagrant
  become: yes
  tasks:
  - name: Running packages against All servers
    include_role:
       name: packages
    when: "'rocketchat_server:jenkin_server' in group_names"
  - name: Running rocketchat role on  All rocketchat  servers
    include_role:
       name: rocketchat
    when: "'rocketchat_server' in group_names"
  - name: Running gitlab role on All gitlab servers
    include_role:
       name: gitlab
    when: "'gitlab_server' in group_names"
  - name: Running jenkins role on All Jenkins  servers
    include_role:
       name: jenkins
    when: "'jenkins_server' in group_names"
  - name: Running playbook against All vault  servers
    include_role:
