# Jenkins  role from ansible-galaxy

- src: geerlingguy.repo-epel
- src: geerlingguy.java
- src: geerlingguy.jenkins
- src: geerlingguy.git
- src: geerlingguy.ansible
- src: tecris.maven


# Git lab role from ansible-galaxy

- src: geerlingguy.gitlab

# Vault role from ansible-galaxy

- src: andrewrothstein.vault
- src: andrewrothstein.vault-app


